# This file is a template, and might need editing before it works on your project.
# Official docker image.
before_script:
- docker info

build:
  stage: build
  tags:
    - yocto
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.ii.org.nz
  - docker build -t docker.ii.org.nz/iichip/poky:$CI_BUILD_REF_NAME .
  - docker push docker.ii.org.nz/iichip/poky:$CI_BUILD_REF_NAME

image: docker.ii.org.nz/iichip/poky:$CI_BUILD_REF_NAME
poky:
  stage: build
  tags: 
    - yocto
  script:
    - git clone -b chip-fido https://gitlab.ii.org.nz/iichip/poky.git
    - ls -la
    - sleep 10
  artifacts:
    name:
      poky
    paths:
      - poky/
  
#build_yocto:
#  stage: deploy
#  tags:
#    - yocto
#  script:
#    - docker pull docker.ii.org.nz/iichip/poky:$CI_BUILD_REF_NAME
#    - docker rm -f docker.ii.org.nz/iichip/poky:$CI_BUILD_REF_NAME || /bin/true
#    - docker run docker.ii.org.nz/iichip/poky:$CI_BUILD_REF_NAME